# index:
#     path: /
#     controller: App\Controller\Index::index
save:
    path: /rest/todo
    methods:    PUT|POST
    controller: App\Controller\ToDo::save
load:
    path: /rest/todo
    methods:    GET
    controller: App\Controller\ToDo::load
